name: optimized_cached_image
description: A library for loading images from network, resizing as per container size and caching while being memory sensitive.
version: 1.0.0
homepage: https://github.com/humblerookie/optimized_cached_image

environment:
  sdk: ">=2.6.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.2.0
  flutter_image_compress: ^0.7.0
  uuid: ^2.0.4
  http: ^0.12.0+4
  path_provider: ^1.6.5
  path: ^1.6.4
  pedantic: ^1.5.0
  flutter_blurhash: ">=0.4.1 <0.6.0"
  sprintf: ^4.0.0
  octo_image: ">=0.1.0 <0.3.0"


dev_dependencies:
  test: 1.9.4
