name: optimized_cached_image
description: A library for loading images from network, resizing as per container size and caching while being memory sensitive.
version: 3.0.1
homepage: https://github.com/humblerookie/optimized_cached_image

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_image_compress: ^2.0.3
  uuid: ^3.0.3
  http: ^0.13.1
  path_provider: ^2.0.15
  path: ^1.8.0
  pedantic: ^1.11.0
  sprintf: ^7.0.0
  octo_image: ^1.0.0
  image: ^4.0.17
  file: ^6.1.0
dev_dependencies:
  test: ^1.16.8